name: Test Examples

# on: workflow_dispatch
on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    # if: github.ref_name == 'main' && github.repository == 'hpcaitech/ColossalAI-Examples' && contains(fromJson('["FrankLeeeee", "ver217", "feifeibear", "kurisusnowdeng"]'), github.actor)
    name: Build ColossalAI and test examples
    runs-on: [self-hosted, gpu]
    timeout-minutes: 20
    container:
      image: nvcr.io/nvidia/pytorch:21.07-py3
      options: --gpus all --rm --ipc=host -v /data/scratch:/data
    steps:
    - name: Install dependencies
      run: |
        pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        pip install -U pip setuptools wheel --user
        pip install pytest tensorboard transformers
    - uses: actions/checkout@v2
      with:
        repository: hpcaitech/ColossalAI
    - name: Install Colossal-AI
      run: |
        pip install -r requirements/requirements.txt
        pip install -v --no-cache-dir .
    - uses: actions/checkout@v2
    - name: Test Feature/Gradient Accumulation
      run: |
        cd features/gradient_accumulation
        python -m torch.distributed.run --standalone --nproc_per_node=1 train_with_engine.py
      env:
        DATA: /data/cifar-10
    - name: Test Feature/Gradient Clipping
      run: |
        cd features/gradient_clipping
        python -m torch.distributed.run --standalone --nproc_per_node=1 train_with_engine.py
      env:
        DATA: /data/cifar-10
    - name: Test Feature/Zero
      run: |
        cd features/zero
        python -m torch.distributed.run --standalone --nproc_per_node=1 train.py
  
